version: 2

models:
  - name: fact_orders
    description: "Core fact table for all retail transactions"
    columns:
      - name: order_id
        tests:
          - not_null

      - name: customer_id
        tests:
          - not_null

      - name: total_value
        tests:
          - not_null

  - name: monthly_revenue
    description: "Monthly revenue KPI mart"